# Tags used for organizing work in the project
backend:
  - '\[(Backend)\]'
frontend:
  - '\[(Frontend|Mocks)\]'
documentation:
  - '\[(Architecture|Wiki|Requirements|User Persona|User Scenarios)\]'
requirements:
  - '\[(Requirements|User Persona|User Scenarios)\]'
user-persona:
  - '\[(User Persona)\]'
user-scenario:
  - '\[(User Scenario(s?))\]'
engine:
  - '\[(Database|DB|Engine)\]'
ci:
  - '\[(CI|Continuous Integration)\]'
full-stack:
  - '\[(Full Stack)\]|\[(Frontend)\]\[(Backend)\]|\[(Backend)\]\[(Frontend)\]'
