import {yupResolver} from '@hookform/resolvers/yup';
import {Box, Button, Divider, Tab, Tabs, Typography} from '@mui/material';
import React from 'react';
import {FormProvider, useForm, useFormState} from 'react-hook-form';
import {FieldValues} from 'react-hook-form/dist/types';
import {useFormAction, useLoaderData, useSubmit} from 'react-router-dom';
import {Investment} from '../Interfaces';
import {updateInvestment} from '../api/InvestmentApi';
import {ConfirmDeleteDialog} from '../components/DialogComponents';
import {InvestmentModelGraph} from '../components/GraphComponents';
import {InvestmentFormDefaults, investmentFormSchema} from '../forms/FormSchema';
import {InvestmentDataForm} from '../forms/InvestmentDataForm';
import {convertDates} from '../api/ConvertUtils';
import {ExpensesTable} from '../forms/ExpenseTable';
import {useSnackbar} from 'notistack';
import { Link } from 'react-router-dom'; 
  
export function AboutPage() { 
	return (<div>
		<h1>About RetireSimple</h1>
		<Box sx={{padding: '2rem'}}>
			<Typography variant='body1'>RetireSimple v1.3.0</Typography>
			<Typography variant='body1'>
				© 2022-2023 Alex Westerman, Ryan Nikolic, All Rights Reserved
			</Typography>
			<br />
			<Typography variant='body1'>
				This software and its source code is licensed under and subject to the terms of
				the <Link to='https://opensource.org/licenses/MIT'>MIT License</Link>
			</Typography>
			<Typography variant='body1'>
				Source Code is available on{' '}
				<Link to='https://github.com/RetireSimple/RetireSimple'>GitHub</Link>.
			</Typography>
			<br />
			<Typography variant='body1'>
				The RetireSimple Logo is based on multiple icons from the FontAwesome free icon
				set. These icons are licensed under the Creative Commons BY 4.0 License as
				stated <Link to='https://fontawesome.com/license/free'>here</Link>.
			</Typography>
			<br />
			<Typography variant='body1'>
				The following libraries are used by the RetireSimple Engine and are subject to
				their respective licenses:
				<ul>
					<li>
						{<Link to='https://github.com/dotnet/runtime'>.NET 6</Link> }
						(MIT License)
					</li>
					<li>
						<Link to='https://github.com/dotnet/efcore'>
							entity framework core 6
						</Link>{' '}
						(MIT License)
					</li>
					<li>
						<Link to='https://github.com/mathnet/mathnet-numerics'>
							math.net numerics
						</Link>{' '}
						(MIT License)
					</li>
				</ul>
			</Typography>
			<br />
			<Typography variant='h6'>DISCLAIMER</Typography>
			<Typography variant='body1'>
				<strong>
					The information provided/generated by RetireSimple and its Engine should not
					be the only source of information you use to make financial decisions. You
					should consult with a certified financial professional (especially one that
					is a certified fiduciary) before making any financial decisions or taking
					any actions related to your finances.
				</strong>
			</Typography>
			<br />
			<Typography variant='body1'>
				<strong>
					RetireSimple and any derivative application using the RetireSimple Engine is
					not responsible for any financial decisions or actions you take based on the
					information provided/generated by RetireSimple.
				</strong>
			</Typography>
		</Box>
	</div>
	);
    
} 