name: Release (Stable) Pipeline

on:
  workflow_dispatch:

jobs:
  build-win:
    name: Build Executable (Windows)
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "Windows x64"
            platform: "win-x64"
          - name: "Windows x86"
            platform: "win-x86"
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Restore NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: RetireSimple.Frontend/pnpm-lock.yaml
      - name: Init Frontend Dependencies
        run: |
          cd RetireSimple.Frontend
          pnpm install
          cd ..
      - name: Build Executable
        run: dotnet publish ./RetireSimple.Backend/RetireSimple.Backend.csproj
          --configuration Release
          --runtime ${{ matrix.platform }}
          --output ./publish/RetireSimple-${{ matrix.platform }}
          -p:PublishProfile=./RetireSimple.Backend/Properties/PublishProfiles/FolderProfile.pubxml
          -p:VersionPrefix=${{ vars.VERSION_PREFIX }}
      - name: Zip Executable
        run: |
          cd publish/RetireSimple-${{ matrix.platform }}
          7z a -tzip ../RetireSimple-${{ matrix.platform }}.zip .
      - name: Upload Artifact for Release Job
        uses: actions/upload-artifact@v3
        with:
          name: RetireSimple-${{ matrix.platform }}
          path: publish/RetireSimple-${{ matrix.platform }}.zip
          retention-days: 1

  build-linux:
    name: Build Executable (Linux)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "Linux x64"
            platform: "linux-x64"
          - name: "Linux ARM64"
            platform: "linux-arm64"
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Restore NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: RetireSimple.Frontend/pnpm-lock.yaml
      - name: Build Frontend
        run: |
          cd RetireSimple.Frontend
          pnpm install
          pnpm run build
          cd ..
      - name: Build Backend Executable
        run: dotnet publish ./RetireSimple.Backend/RetireSimple.Backend.csproj
          --configuration Release
          --runtime ${{ matrix.platform }}
          --output ./publish/RetireSimple-${{ matrix.platform }}
          -p:PublishProfile=./RetireSimple.Backend/Properties/PublishProfiles/FolderProfile.pubxml
          -p:VersionPrefix=${{ vars.VERSION_PREFIX }}
      - name: Zip Executable
        run: |
          cd publish/RetireSimple-${{ matrix.platform }}
          chmod +x RetireSimple.Backend
          7z a -tzip ../RetireSimple-${{ matrix.platform }}.zip .
      - name: Upload Artifact for Release Job
        uses: actions/upload-artifact@v3
        with:
          name: RetireSimple-${{ matrix.platform }}
          path: publish/RetireSimple-${{ matrix.platform }}.zip
          retention-days: 1

  build-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Restore NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Build NuGet Package
        run: dotnet pack ./RetireSimple.Backend/RetireSimple.Backend.csproj
          --configuration Release
          --output ./publish
          -p:VersionPrefix=${{ vars.VERSION_PREFIX }}
      - name: Add GitHub Packages Source
        run: dotnet nuget add source 
          --username USERNAME
          --password ${{ secrets.GITHUB_TOKEN }} 
          --store-password-in-clear-text 
          --name github 
          "https://nuget.pkg.github.com/RetireSimple/index.json"
      - name: Push NuGet Package
        run: dotnet nuget push ./publish/RetireSimple.Engine.*.nupkg
          --api-key ${{ secrets.GITHUB_TOKEN }}
          --source github
      - name: Upload Artifact for Release Job
        uses: actions/upload-artifact@v3
        with:
          name: RetireSimple.Backend.nupkg
          path: publish/RetireSimple.Engine.*.nupkg
          retention-days: 1
          
          
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-win, build-linux, build-nuget]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Nightly
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ vars.VERSION_PREFIX }}
          name: EDIT ME
          allowUpdates: true
          draft: false
          prerelease: False
          artifacts: |
            RetireSimple-*/RetireSimple-*.zip
            RetireSimple-*/RetireSimple.Engine.*.nupkg

