name: Release (Stable) Pipeline

on:
  workflow_dispatch:

jobs:
  build-exec:
    name: Build Executable (Windows)
    runs-on: windows-latest
    needs: [engine-build, frontend-build, get-info]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "Windows x64"
            platform: "win-x64"
          - name: "Windows x86"
            platform: "win-x86"
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Restore NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: RetireSimple.Frontend/pnpm-lock.yaml
      - name: Init Frontend Dependencies
        run: |
          cd RetireSimple.Frontend
          pnpm install
          cd ..
      - name: Build Executable
        run: dotnet publish ./RetireSimple.Backend/RetireSimple.Backend.csproj
          --configuration Release
          --runtime ${{ matrix.platform }}
          --output ./publish/RetireSimple-${{ matrix.platform }}
          -p:PublishProfile=./RetireSimple.Backend/Properties/PublishProfiles/FolderProfile.pubxml
          -p:VersionPrefix=${{ vars.VERSION_PREFIX }}
      - name: Zip Executable
        run: |
          cd publish/RetireSimple-${{ matrix.platform }}
          7z a -tzip ../RetireSimple-${{ matrix.platform }}.zip .
      - name: Upload Artifact for Release Job
        uses: actions/upload-artifact@v3
        with:
          name: RetireSimple-${{ matrix.platform }}
          path: publish/RetireSimple-${{ matrix.platform }}.zip
          retention-days: 1

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-exec]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
      - name: Nightly
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ vars.VERSION_PREFIX }}
          name: EDIT ME
          allowUpdates: true
          draft: false
          prerelease: False
          artifacts: RetireSimple-*/RetireSimple-*.zip

