name: TEST ONLY - Nightly Builder
on:
  pull_request:
    branches: [main]

jobs:
  get-info:
    name: Get Relevant Project Information
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
      hash: ${{ steps.commithash.outputs.hash }}
      prev-hash: ${{ steps.prevcommithash.outputs.prevhash }}
    steps:
      - uses: actions/checkout@v3
      - name: Get date for Nightly Release body
        id: date
        run: echo "date=$(date +'%Y-%m-%d %H:%M:%S %Z')" >> $GITHUB_OUTPUT
      - name: Get Short Commit Hash for Nightly Versioning
        id: commithash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT



  build-macos:
    name: MacOS Build
    runs-on: macos-latest
    needs: [get-info]
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: MacOS x64 (Intel)
            platform: "osx-x64"
          - name: "MacOS ARM64 (Apple Silicon)"
            platform: "osx.12-arm64"
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Restore NuGet Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: RetireSimple.Frontend/pnpm-lock.yaml
      - name: Build Frontend
        run: |
          cd RetireSimple.Frontend
          pnpm install
          pnpm run build
          cd ..
      - name: Build Executable
        run: dotnet publish ./RetireSimple.Backend/RetireSimple.Backend.csproj
          --configuration Release
          --runtime ${{ matrix.platform }}
          --output ./publish/RetireSimple-${{ matrix.platform }}
          -p:PublishProfile=./RetireSimple.Backend/Properties/PublishProfiles/FolderProfile.pubxml
          -p:VersionPrefix=${{ vars.VERSION_PREFIX }}
          -p:VersionSuffix=nightly-${{ needs.get-info.outputs.hash }}
      - name: Copy Frontend Resources
        run: |
          mkdir -p publish/RetireSimple-${{ matrix.platform }}/wwwroot
          cp -r RetireSimple.Frontend/build/* publish/RetireSimple-${{ matrix.platform }}/wwwroot
      - name: Install + Setup Platypus
        run: |
          brew install platypus
          sudo ln -s /usr/local/Cellar/platypus/5.3/share/platypus /usr/local/share/platypus
        # Unfortunately, the platypus executable expects its resources in /usr/local/share/platypus
        # and not the homebrew cellar. But my god symlinks are based
      - name: Create MacOS App Bundle
        run: |
          cd publish/RetireSimple-${{ matrix.platform }}
          echo "Creating Init Script"
          echo '#!/bin/sh' > init.sh
          echo './RetireSimple.Backend' > init.sh
          chmod +x init.sh
          chmod +x RetireSimple.Backend
          platypus \
            --name 'RetireSimple' \
            --interface-type 'Text Window' \
            --interpreter '/bin/sh' \
            --author 'Alex Westerman, Ryan Nikolic' \
            --app-version ${{ vars.VERSION_PREFIX }}-nightly-${{ needs.get-info.output.hash }} \
            --overwrite \
            --bundle-identifier org.RetireSimple.RetireSimple \
            --bundled-file './appsettings.Development.json' \
            --bundled-file './appsettings.json' \
            --bundled-file './libe_sqlite3.dylib' \
            --bundled-file './packages.lock.json' \
            --bundled-file './RetireSimple.Backend' \
            --bundled-file './wwwroot' \
            './init.sh'
          cd ../..
      - name: Ad-hoc sign to allow FS access?
        run: codesign --force -s - publish/RetireSimple-${{ matrix.platform }}/RetireSimple.app
      - name: Zip Bundled Executable
        run: |
          cd publish/RetireSimple-${{ matrix.platform }}
          7z a -tzip ../RetireSimple-${{ matrix.platform }}.zip RetireSimple.app
      - name: Upload Artifact for Release Job
        uses: actions/upload-artifact@v3
        with:
          name: RetireSimple-${{ matrix.platform }}
          path: publish/RetireSimple-${{ matrix.platform }}.zip
          retention-days: 1